#!/bin/bash

## SGE
#$ -N MERVIN_JOBNAME
#$ -q MERVIN_Q_SGE
#$ -e MERVIN_MSG_FOLDER/MERVIN_JOBNAME.msg
#$ -R yes

## SLURM
#SBATCH -J MERVIN_JOBNAME
#SBATCH -p MERVIN_Q_SLURM
#SBATCH -o MERVIN_MSG_FOLDER/MERVIN_JOBNAME.msg
#SBATCH -N 1
#SBATCH --ntasks-per-node=1


workdir=MERVIN_WORKDIR
i_side=MERVIN_I
j_side=MERVIN_J


## PROGRESIVE LAUNCH (:,:)
cd $workdir
for i in `seq -w 0 ${i_side}`; do
  filename="ep.${i}.XX"

  i_min="$i"
  i_max="$i"
  j_min=0
  j_max=$j_side
  if [ "$i" == "00" ]; then
    coord="MERVIN_COORD"
  else
    coord="pes.`printf %02d $((10#$i-1))`.00.crd"
  fi

  outfile="${filename}.out"
  jobfile="${filename}.job"
  inputfile="${filename}.inp"
  logfile="${filename}.log"

  echo "#!/bin/bash "                                  > ${jobfile}
  echo ""                                              >> ${jobfile}
  echo "#$ -N $filename "                              >> ${jobfile}
  echo "#$ -q MERVIN_Q_SGE "                           >> ${jobfile}
  echo "#$ -e MERVIN_MSG_FOLDER/${filename}.msg "              >> ${jobfile}
  echo "#$ -R yes "                                    >> ${jobfile}
  echo "#$ -l h='!node009.cm.cluster' "                >> ${jobfile}
  echo ""                                              >> ${jobfile}
  echo "#SBATCH -J $filename "                         >> ${jobfile}
  echo "#SBATCH -p MERVIN_Q_SLURM "                    >> ${jobfile}
  echo "#SBATCH -o MERVIN_MSG_FOLDER/${filename}.msg "         >> ${jobfile}
  echo "#SBATCH -N 1 "                                 >> ${jobfile}
  echo "#SBATCH --ntasks-per-node=1 "                  >> ${jobfile}
  echo ""                                              >> ${jobfile}
  echo "cd $workdir"                                   >> ${jobfile}
  echo "echo \"${i_min} ${i_max} ${j_min} ${j_max} ${coord} ${outfile}\" > ${inputfile}" >> ${jobfile}
  echo "./a.out < ${inputfile} > ${logfile}"           >> ${jobfile}
  echo "rm ${inputfile}"                               >> ${jobfile}

  { qsub ${jobfile} ; } 2>/dev/null
  { sbatch ${jobfile} ; } 2>/dev/null

  while [ ! -f "pes.${i}.00.crd" ]; do
    sleep 1
  done

done
