#!/bin/bash

#################################################
###               MERVIN MONROE               ###
#################################################
#     A lazy interface for fDynamo software     #
#################################################

#                by Sergio Boneta


## CONFIGURATION:
  # set $mervinmonroe variable to the main folder path (in '.bashrc')
  # example: export mervinmonroe="/home/user/bin/mervinmonroe"

  # include this variable in $PATH if desired
  # example: export PATH=$PATH:"$mervinmonroe"


## USAGE:   mervinmonroe [options]


##  DEFAULT VARIABLES  ##############################################

  export workdir=`pwd`
  export systems_subfolder="systems"
  export scripts_subfolder="bin"
  export templates_subfolder="templates"

  export mervinmonroe_version="0.1.6 - 25022020"

##  SCRIPT  #########################################################
  ## Execute configuration file
    source ${mervinmonroe}/.mervinconfig

  ## Check if the $mervinmonroe variable has been set
  if [ "$mervinmonroe" == "" ]; then
    echo "ERROR: no '\$mervinmonroe' path variable set"
    exit
  fi

  ## Checks if no arguments are in the input
  if [ "$1" == "" ]; then
    echo "ERROR: No input arguments. Use -h for help."
    exit
  fi

  ## Input arguments assignment
  subscript="$1"
  shift
  case $subscript in
    "info" )                     # information
      ${mervinmonroe}/${scripts_subfolder}/info.sh $@
      ;;
    "update" )                   # update Mervin Monroe
      read -p "Update Mervin Monroe software? (y/n): " update_response
      if [ "$update_response" == "y" ] || [ "$update_response" == "yes" ]; then
        cd $mervinmonroe
        git fetch --all
        git reset --hard origin/master
        if [ "$?" == 0 ]; then
          echo "## Mervin Monroe updated from GitHub succesfully!"
        else
          echo "ERROR: Something went wrong while updating from GitHub."
          cd - /dev/null 2>&1
          exit
        fi
        bash .mervinconfig
        cd - /dev/null 2>&1
      else
        echo "Update cancelled. Exiting."
        exit
      fi
      ;;
    "import" )                   # system importer
      ${mervinmonroe}/${scripts_subfolder}/import.sh $@
      ;;
    "compile"|"c" )              # Dynamo compilation
      ${mervinmonroe}/${scripts_subfolder}/compile.sh $@
      ;;
    "minimizator"|"mini" )       # minimization
      ${mervinmonroe}/${scripts_subfolder}/minimizator.sh $@
      ;;
    "pel"|"scan" )               # PEL calculation launcher
      ${mervinmonroe}/${scripts_subfolder}/pel.sh $@
      ;;
    "pes" )                      # PES calculation launcher
      ${mervinmonroe}/${scripts_subfolder}/pes.sh $@
      ;;
    "locate" )                   # locator of minima and TS
      ${mervinmonroe}/${scripts_subfolder}/locate.sh $@
      ;;
    "irc" )                      # irc
      ${mervinmonroe}/${scripts_subfolder}/irc.sh $@
      ;;
    "pmf" )                      # pmf
      ${mervinmonroe}/${scripts_subfolder}/pmf.sh $@
      ;;
    "tools"|"t" )                # tools
      subtool=$1
      shift
      if [ "$subtool" == "-h" ] || [ "$subtool" == "--help" ]; then
        ls ${mervinmonroe}/${scripts_subfolder}/tools/ | grep -v "ecmb.*"
        exit
      fi
      if [[ -r "${mervinmonroe}/${scripts_subfolder}/tools/$subtool" ]]; then
          ${mervinmonroe}/${scripts_subfolder}/tools/$subtool $@
      else
        echo "ERROR: Tool '$subtool' not found."
        exit
      fi
      ;;
    "-h"|"--help" )              # print help and exit
      echo "---------------  MERVIN MONROE  ---------------"
      echo "     A lazy interface for fDynamo software     "
      echo
      echo "Version $mervinmonroe_version"
      echo
      echo "USAGE:   mervinmonroe  <options>"
      echo
      echo "OPTIONS:                                     "
      echo " info                         information"
      echo " update                       update Mervin Monroe"
      echo " import                       system importer"
      echo " compile | c                  Dynamo compilation"
      echo " minimizator | mini           minimizator"
      echo " pel | scan                   PELine calculation"
      echo " pes                          PES calculation"
      echo " locate                       locate minima and TS"
      echo " irc                          IRC calculation"
      echo " pmf                          PMF calculation"
      echo " tools | t                    tools (miscellaneous)"
      echo " -h | --help                  print this help and exit"
      echo
      exit ;;
    *)
      echo "ERROR: Wrong option '$subscript'. Use -h for help."
      exit ;;
  esac
