#!/bin/bash

## SGE
#$ -N MERVIN_JOBNAME
#$ -q MERVIN_Q_SGE
#$ -e MERVIN_MSG_FOLDER/MERVIN_JOBNAME.msg
#$ -R yes

## SLURM
#SBATCH -J MERVIN_JOBNAME
#SBATCH -p MERVIN_Q_SLURM
#SBATCH -o MERVIN_MSG_FOLDER/MERVIN_JOBNAME.msg
#SBATCH -N 1
#SBATCH --ntasks-per-node=1

workdir=MERVIN_WORKDIR
i_side=MERVIN_I
j_side=MERVIN_J

cd $workdir

## launch
for i in `seq -w 0 $i_side`; do
  for j in `seq -w 0 $j_side`; do

    filename="sp.${i}.${j}"

    jobfile="${filename}.job"
    inputfile="${filename}.inp"
    logfile="${filename}.log"

    mkdir $filename
    cd $filename

    echo "#!/bin/bash "                                  > ${jobfile}
    echo ""                                              >> ${jobfile}
    echo "#$ -N $filename "                              >> ${jobfile}
    echo "#$ -q MERVIN_Q_SGE "                           >> ${jobfile}
    echo "#$ -e $HOME/msg/${filename}.msg "              >> ${jobfile}
    echo "#$ -R yes "                                    >> ${jobfile}
    echo "#$ -pe mp8 8 "                                 >> ${jobfile}
    echo "#$ -l h='!node009.cm.cluster' "                >> ${jobfile}
    echo ""                                              >> ${jobfile}
    echo "#SBATCH -J $filename "                         >> ${jobfile}
    echo "#SBATCH -p MERVIN_Q_SLURM "                    >> ${jobfile}
    echo "#SBATCH -o $HOME/msg/${filename}.msg "         >> ${jobfile}
    echo "#SBATCH -N 1 "                                 >> ${jobfile}
    echo "#SBATCH --ntasks-per-node=8 "                  >> ${jobfile}
    echo ""                                              >> ${jobfile}
    echo "cd $workdir/$filename"                         >> ${jobfile}
    echo "echo \"${i} ${j}\" > ${inputfile}"             >> ${jobfile}
    echo "../a.out < ${inputfile} > ${logfile}"          >> ${jobfile}
    echo "rm ${inputfile}"                               >> ${jobfile}

    { qsub ${jobfile} ; } 2>/dev/null
    { sbatch ${jobfile} ; } 2>/dev/null
    sleep 1
    cd -

  done
done
