#!/bin/bash

## SGE
#$ -N MERVIN_JOBNAME
#$ -q MERVIN_Q_SGE
#$ -e $HOME/msg/MERVIN_JOBNAME.msg
#$ -R yes

## SLURM
#SBATCH -J MERVIN_JOBNAME
#SBATCH -p MERVIN_Q_SLURM
#SBATCH -o $HOME/msg/MERVIN_JOBNAME.msg
#SBATCH -N 1
#SBATCH --ntasks-per-node=1


workdir=MERVIN_WORKDIR
i_side=MERVIN_I

## i SIDE (:)
filename="ep.XX"

i_min=0
i_max=$i_side
coord="MERVIN_COORD"

outfile="${filename}.out"
inputfile="${filename}.inp"
logfile="${filename}.log"


cd $workdir
echo -e "${i_min} ${i_max} ${coord} ${outfile}" > ${inputfile}
./a.out < ${inputfile} > ${logfile}
rm ${inputfile}
