#!/bin/bash

## SGE
#$ -q MERVIN_Q_SGE
#$ -N MERVIN_JOBNAME
#$ -e $HOME/msg/MERVIN_JOBNAME.msg
#$ -R yes

## SLURM
#SBATCH -J MERVIN_JOBNAME
#SBATCH -p MERVIN_Q_SLURM
#SBATCH -o $HOME/msg/MERVIN_JOBNAME.msg
#SBATCH -N 1
#SBATCH --ntasks-per-node=1

workdir=MERVIN_WORKDIR
cd $workdir
./a.out > MERVIN_JOBNAME.log
