#!/bin/bash

## SGE
#$ -N MERVIN_JOBNAME
#$ -q MERVIN_Q_SGE
#$ -e MERVIN_MSG_FOLDER/MERVIN_JOBNAME.msg
#$ -R yes

## SLURM
#SBATCH -J MERVIN_JOBNAME
#SBATCH -p MERVIN_Q_SLURM
#SBATCH -o MERVIN_MSG_FOLDER/MERVIN_JOBNAME.msg
#SBATCH -N 1
#SBATCH --ntasks-per-node=1


workdir=MERVIN_WORKDIR
i_side=MERVIN_I
j_side=MERVIN_J

cd $workdir

## launch PMF
for i in `seq -w 0 ${i_side}`; do
  for j in `seq -w 0 ${j_side}`; do

    filename="pmf.${i}.${j}"

    jobfile="${filename}.job"
    inputfile="${filename}.inp"
    logfile="${filename}.log"

    echo "#!/bin/bash "                                  > ${jobfile}
    echo ""                                              >> ${jobfile}
    echo "#$ -N $filename "                              >> ${jobfile}
    echo "#$ -q MERVIN_Q_SGE "                           >> ${jobfile}
    echo "#$ -e MERVIN_MSG_FOLDER/${filename}.msg "              >> ${jobfile}
    echo "#$ -R yes "                                    >> ${jobfile}
    echo "#$ -l h='!node009.cm.cluster' "                >> ${jobfile}
    echo ""                                              >> ${jobfile}
    echo "#SBATCH -J $filename "                         >> ${jobfile}
    echo "#SBATCH -p MERVIN_Q_SLURM "                    >> ${jobfile}
    echo "#SBATCH -o MERVIN_MSG_FOLDER/${filename}.msg "         >> ${jobfile}
    echo "#SBATCH -N 1 "                                 >> ${jobfile}
    echo "#SBATCH --ntasks-per-node=1 "                  >> ${jobfile}
    echo ""                                              >> ${jobfile}
    echo "cd $workdir"                                   >> ${jobfile}
    echo "echo \"${i} ${j}\" > ${inputfile}"             >> ${jobfile}
    echo "./a.out < ${inputfile} > ${logfile}"           >> ${jobfile}
    echo "rm ${inputfile} borra_${i}.${j}"               >> ${jobfile}

    { qsub ${jobfile} ; } 2>/dev/null
    { sbatch ${jobfile} ; } 2>/dev/null
    sleep 1

  done
done
